name: EhSoja

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - 'main'

jobs:
  buildServer:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7.3
      uses: actions/setup-python@v2
      with:
        python-version: "3.7.3"
    - name: Installing dependencies
      run: |
        cd src
        cd server
        cd imageRecognition
        python -m pip install --upgrade pip
        pip install -r requirements.txt
